Fixed the clickable zone of the text field
solid-software/languagetool_textfield pull request #47
Opened 2023-06-07 09:52 UTC by silverkate

2023-06-30 19:16 UTC, solid-danylokhvan commented
**TEST REPORT**

2023-07-03 10:16 UTC, solid-yuriiprykhodko requested changes
Please remove redundant comments, beside other things.

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +      text: textAfterMistake.isEmpty ? ' ' : textAfterMistake,
Not clear what this can be. 
WDYM by "messed up"?
Why return a space if the mistake is at the end of the text?

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    if (localOffset == null) return null;
Please remove the "watery water" comments. 

```suggestion
    if (localOffset == null) return null;
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    final renderBox = context.findRenderObject() as RenderBox?;
Use meaningful variable names instead of comments.
```suggestion
    final textFieldRenderBox = context.findRenderObject() as RenderBox?;
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    // Convert the global position to local offset
```suggestion
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    final elementHeight = renderBox?.size.height ?? 0;
```suggestion
    final textBoxHeight = renderBox?.size.height ?? 0;
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    if (localOffset.dy < 0 || localOffset.dy > elementHeight) return null;
```suggestion
    final isOffsetOutsideTextBox = localOffset.dy < 0 || localOffset.dy > elementHeight
    if (isOffsetWithinTextBox) return null;
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    if (localOffset.dy < 0 || localOffset.dy > elementHeight) return null;
It's also good tone to place value boundaries by order, as if we were describing a mathematical range.

```suggestion
    final isOffsetOutsideTextBox = localOffset.dy < 0 || elementHeight < localOffset.dy
    if (isOffsetWithinTextBox) return null;
```

This reads as "localOffser.dy is outside the [0..elementHeight] range".

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    // Create a text painter to measure the text layout
```suggestion
```

2023-07-03 10:16 UTC, solid-yuriiprykhodko commented on lib/utils/extensions/iterable_extension.dart
> +}
https://pub.dev/documentation/collection/latest/collection/IterableExtension/firstWhereOrNull.html

```suggestion
import 'package:collections/collections.dart';
```

2023-07-03 16:45 UTC, solid-danylokhvan commented on lib/utils/extensions/iterable_extension.dart
> +}
But I want to avoid using packages in our package

2023-07-04 09:17 UTC, solid-yuriiprykhodko commented on lib/utils/extensions/iterable_extension.dart
> +}
`collections` is a common enough package, I don't think it makes sense to avoid it. Let's add it here and remove the custom implementation.

My reasoning is -- the package is tried and tested, while maintaining a set of utilities like this incurs overhead. Ideally I'd want to see some unit-tests for this function, the tests and the function itself have to be maintained etc.

Why do all that when we have a ready-made solution in a package. Managing dependencies is a simpler task than what I described above.

2023-07-04 09:19 UTC, solid-yuriiprykhodko requested changes
Please remove the custom collection util and use the package. Otherwise LGTM.

2023-07-04 13:27 UTC, solid-yuriiprykhodko approved these changes

2023-07-04 17:23 UTC, merged