Feat/remove language tool package
solid-software/languagetool_textfield pull request #48
Opened 2023-06-08 06:56 UTC by silverkate

2023-06-08 08:44 UTC, solid-vovabeloded commented on lib/beans/category.dart
> +  String id;
I think we should make all model fields final.

2023-06-08 08:47 UTC, solid-vovabeloded commented on lib/beans/rule.dart
> +  String id;
Does it make sense to map this id into Enum?

2023-06-08 08:47 UTC, solid-vovabeloded commented on lib/beans/rule.dart
> +  String issueType;
Add enum for this field as well?

2023-06-08 08:49 UTC, solid-vovabeloded commented on lib/beans/type.dart
> +class Type {
Does it make sense to rename it to 'MistakeType' since we already have a 'Type' class in dart?

2023-06-08 08:49 UTC, solid-vovabeloded commented on lib/beans/type.dart
> +  String typeName;
Can we create a enum for this field as well? Overall, probably, we can replace this entire class with enum.

2023-06-08 08:51 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +class LanguageTool {
What do you think about 'LanguageToolClient'?

2023-06-08 08:52 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +  final String language;
I think it would be better to pass the language directly to the method to be able to switch the language without client recreation.

2023-06-08 08:53 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +          .then(
It would be more readable to use 'await' in such cases.

2023-06-08 08:53 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +  Future<List<WritingMistake>> check(String text) => http
The block body will fit better here from my point of view.

2023-06-08 08:55 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +        (error, stackTrace) => throw Exception(error),
What is the point of wrapping the existing exception into another exception? I'd say we do not need to catch it here if we are not going to throw any package-specific exceptions instead.

2023-06-08 08:56 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
> +  }
Please, use 'Uri' class for URI encoding.

2023-06-08 09:05 UTC, solid-vovabeloded commented on lib/core/network/language_tool.dart
What do you think about moving this file into the 'client' package?

2023-06-08 11:29 UTC, silverkate commented on lib/beans/rule.dart
> +  String id;
As I understand there are way too many possible ids... 603 pages of English only 😅😅

https://community.languagetool.org/rule/list?lang=en

2023-06-08 11:43 UTC, silverkate commented on lib/beans/type.dart
> +class Type {
I removed the Type class as there is MistakeType enum present

2023-06-08 16:58 UTC, solid-vovabeloded commented on lib/client/language_tool_client.dart
> +    );
Please, use `Uri.encodeQueryComponent` here.

2023-06-08 16:59 UTC, solid-vovabeloded commented on lib/beans/context.dart
> +class Context {
```suggestion
class MistakeContext {
```
?

2023-06-08 17:05 UTC, solid-vovabeloded commented on lib/client/language_tool_client.dart
> +      json.decode(utf8.decode(result.bodyBytes)) as Map<String, dynamic>,
```suggestion
      json.decode(result.body) as Map<String, dynamic>,
```

2023-06-08 17:06 UTC, solid-vovabeloded commented on lib/core/enums/mistake_type.dart
> +  }
NIT: we can just add a value property instead of doing this switch

2023-06-27 17:25 UTC, solid-danylokhvan commented on lib/client/language_tool_client.dart
> +    String language = 'auto',
Just wanted to confirm if we want to keep the autoselected language feature. I noticed that it sometimes picks up wrong things in English sentences.

<img width="302" alt="Снимок экрана 2023-06-27 в 20 20 52" src="https://github.com/solid-software/languagetool_textfield/assets/113029066/c9f3bb34-d237-484e-ab1e-c156a2279fe8">

2023-07-04 10:36 UTC, solid-vovabeloded commented on lib/client/language_tool_client.dart
> +    String language = 'auto',
I think we want to add a language selection feature in a separate PR after this one.

2023-07-04 10:57 UTC, solid-vovabeloded requested changes

2023-07-04 10:57 UTC, solid-vovabeloded commented on lib/beans/match.dart
Let's rename `beans` => `model` and move it to the `core` folder.

2023-07-04 10:57 UTC, solid-vovabeloded commented on lib/beans/mistake_context.dart
> +class MistakeContext {
Do we need this model? Maybe it makese sense to remove it?

2023-07-04 10:57 UTC, solid-vovabeloded commented on lib/core/enums/mistake_type.dart
> +      (type) => type.toString().split('.').last == lowercasedValue,
Would it be better to have something like a `value` field in this enum and use it to parse the enum value from a string?

2023-07-04 15:04 UTC, solid-vovabeloded approved these changes
Please, resolve this suggestion and you'll be good to go.

2023-07-04 15:04 UTC, solid-vovabeloded commented on lib/domain/writing_mistake.dart
> +    required String shortMessage,
I'd suggest making these parameters optional like we usually do for `copyWith` methods.

2023-07-04 17:43 UTC, merged