Intelligent highlight
solid-software/languagetool_textfield pull request #50
Opened 2023-06-27 16:51 UTC by solid-danylokhvan

2023-06-27 19:42 UTC, solid-yuriiprykhodko requested changes
Please add a test plan, and provide testing results.

Off the top of my head, we should test:
- copy-pasting words/sentences
- editing test in the beginning, middle and end of the text
- selecting and removing large chunks of text
- combinations of the above

For all these cases, we must ensure that the custom styling and interactivity works appropriately.

2023-06-27 21:36 UTC, solid-danylokhvan commented
**TEST REPORT**

1. copy-pasting words/sentences

https://github.com/solid-software/languagetool_textfield/assets/113029066/e4b9bf02-133a-4050-abc2-5ea0b17969b2

2. editing text in the beginning, middle and end of the text

https://github.com/solid-software/languagetool_textfield/assets/113029066/0c4f18ce-0263-461e-8641-0c03d2606b2e

3. selecting and removing large chunks of text

https://github.com/solid-software/languagetool_textfield/assets/113029066/967cc48a-8d6b-4373-9e45-b4c6e58bf5f3

4. combinations of the above

https://github.com/solid-software/languagetool_textfield/assets/113029066/af06d6e1-2516-423e-970e-200175ec05f9

2023-07-03 10:34 UTC, solid-yuriiprykhodko requested changes

2023-07-03 10:34 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +      // Retrieve the result and error information from the MistakesWrapper
Redundant comments.
```suggestion
    languageCheckService.findMistakes(newText).then((value) {
```

2023-07-03 10:34 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +      // Retrieve the result and error information from the MistakesWrapper
Also, no good reason to use Future.then callbacks here. Let's revert to `async-await` and reduce nesting.

2023-07-03 10:34 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +      _lastRequestId = 0;
This shouldn't be done inside this class.

We want to update the UI using the latest request result, correct? Sounds like we need another `LanguageToolService` modifier for this, similar to how we implement debounce -- one that would discard stale results and return null.

2023-07-03 10:34 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +  List<Mistake> _filterMistakesOnChanged(String newText) {
This function needs some decomposition.
A good rule of thumb is no more than 1 level of code nesting per function (e.g. a single loop, or a single if/if-else condition). 
Here we have 3, with  `for - if - if`.

Selection handling is unreadable -- maybe we need a set of utility functions or a class that would encapsulate these comparisons.

2023-07-03 16:04 UTC, solid-danylokhvan commented on lib/core/controllers/colored_text_editing_controller.dart
> +      _lastRequestId = 0;
I've added the request id field to the debounce class

2023-07-04 11:44 UTC, solid-yuriiprykhodko commented on lib/implementations/debounce_lang_tool_service.dart
> +  int _lastRequestId = 0;
Not sure this also is the right place for tracking latest requests. How will this work with the Throttline 
Let's make its own class for this. Something like "KeepLatestResponseService"

Also, here's how I see this: 

Whenever we make a new request, we should discard results of the previous one. We don't really need to track and IDs in order to do it.
See https://pub.dev/documentation/async/latest/async/CancelableOperation-class.html.

2023-07-04 12:11 UTC, solid-yuriiprykhodko commented on lib/utils/extensions/selection_extension.dart
> +      (start > mistake.offset && start <= mistake.endOffset);
```suggestion
  bool overlapsWith(Mistake mistake) =>
      (mistake.offset < end && end <= mistake.endOffset) ||
      (mistake.offset < start && start <= mistake.endOffset);
```

2023-07-04 12:18 UTC, solid-yuriiprykhodko commented on lib/utils/extensions/selection_extension.dart
> +extension SelectionExtension on TextSelection {
You did extract the comparisons each into their own function -- but we could refine the operations a bit more.
In previous comment, I meant something more general-purpose and easy to reason about:
```dart
class ClosedRange {
  final int start;
  final int end;
  const ClosedRange(this.start, this.end);

  bool isAfter(int point) {
    return point > min(start, end);
  }

  bool contains(int point) {
    return start <= point && point <= end;
  }

  bool containsRange(ClosedRange other) {
    return contains(other.start) && contains(other.end);
  }
  
  bool overlapsWith(ClosedRange other) {
    return contains(other.start) || contains(other.end);
  }
}
```

2023-07-05 11:16 UTC, solid-yuriiprykhodko requested changes

2023-07-05 11:16 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +          : newMistakes.add(mistake);
1. Let's turn this into a generator function.
2. selection.base.offset is going to be the location of the _caret_, correct? Having no selection range is probably going to be our most common use case, perhaps handling just a plain _caret cursor_ and a selection _range_ should be handled differently?

2023-07-05 11:16 UTC, solid-yuriiprykhodko commented on lib/implementations/keep_latest_response_service.dart
> +  }
To provide best service, we need to kick off the `action` _before_ we do anything else.
Let's reorder things:
1. Run action
2. cancel previous operation if needed
3. store pointer to current action

2023-07-05 19:49 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    if (shouldSkipOffsetAdjustment) return null;
```suggestion
    final caretLocation = selection.base.offset;
    final isCaretOnMistake = mistakeRange.contains(caretLocation);
    
    // Don't highlight mistakes on changed text until we get an update from the API.
    if (isCaretOnMistake) return null;
```

2023-07-05 19:51 UTC, solid-yuriiprykhodko commented on lib/core/controllers/colored_text_editing_controller.dart
> +    if (shouldSkipOffsetAdjustment) return null;
1. `ClosedRange::overlapsWith` is always true if `ClosedRange::containsRange` is true.
2. Descriptive naming
```suggestion
    final hasSelectedTextChanged = selectionRange.overlapsWith(mistakeRange);

    if (hasSelectedTextChanged) return null;
```

2023-07-05 19:55 UTC, solid-yuriiprykhodko requested changes
A lot better and easy to reason about.
A few more readability changes and we're good to go.

2023-07-05 19:55 UTC, solid-yuriiprykhodko commented on lib/implementations/keep_latest_response_service.dart
> +import 'package:async/async.dart';
Move this to /utils. This is not an implementation of a LangToolService.

2023-07-07 06:45 UTC, solid-yuriiprykhodko approved these changes
LGTM!

2023-07-07 08:47 UTC, merged