Arabic Support
solid-software/languagetool_textfield pull request #75
Opened 2024-01-28 05:22 UTC by Semsem-programmer

This fork supports Arabic LanguageToolTextField, with properties:
1- Support Arabic symbols. Showing correctly.
2- Make LanguageToolTextField left to right alignment.

2024-01-29 17:55 UTC, yurii-prykhodko-solid requested changes
Nice addition! Left a few comments. Please make sure you run `dart format` on the checked-in code.

2024-01-29 17:55 UTC, yurii-prykhodko-solid commented on lib/presentation/language_tool_text_field.dart
> +		this.textDirection = TextDirection.rtl,
Manually specifying directionality makes sense for apps that are expected to support multiple languages at once -- but even then I'd consider creating scoped [Directionality](https://api.flutter.dev/flutter/widgets/Directionality-class.html) contexts.

Nevertheless, it's still sensible to have these arguments available.

But if we want them to be part of the main package -- I suggest we make them nullable and optional, `null` as default.
```suggestion
		this.textAlign,
		this.textDirection,
```

2024-01-29 17:55 UTC, yurii-prykhodko-solid commented on lib/presentation/language_tool_text_field.dart
> +							textDirection: widget.textDirection,
I don't see field declarations for `textAlign` and `textDirection` in the Widget.

2024-01-29 17:55 UTC, yurii-prykhodko-solid commented on lib/client/language_tool_client.dart
> +			json.decode(utf8.decode(result.bodyBytes)) as Map<String, dynamic>,
No commented-out code in VCS, please.
```suggestion
			json.decode(utf8.decode(result.bodyBytes)) as Map<String, dynamic>,
```

2024-01-29 18:12 UTC, illia-romanenko commented
I would also suggest to format the code as well - now it looks off.

2024-01-29 18:25 UTC, yurii-prykhodko-solid commented on lib/presentation/language_tool_text_field.dart
> +		this.textDirection = TextDirection.rtl,
Correction: we won't be able to make textAlign nullable -- instead we should copy the default value from [TextField constructor](https://api.flutter.dev/flutter/material/TextField/TextField.html).

```suggestion
		this.textAlign = TextAlign.start,
		this.textDirection,
```

2024-01-29 19:17 UTC, Semsem-programmer commented on lib/presentation/language_tool_text_field.dart
> +		this.textDirection = TextDirection.rtl,
Ok, this is better!

2024-01-30 10:25 UTC, solid-yuriiprykhodko approved these changes
LGTM!

2024-01-30 10:27 UTC, merged