Add some properties (`cursorColor`, `onTextChange`, `focusNode`, `onTextSubmitted`, ...)  for TextField
solid-software/languagetool_textfield pull request #83
Opened 2024-07-24 07:45 UTC by dab246

## Descriptions

- I want to use some properties of `TextField` in my project.

2024-07-25 00:51 UTC, illia-romanenko commented
Hi @dab246, thanks for the PR!

I just merged one with padding - that looks to be conflicting with yours, could you please solve conflicts and make sure that checks are not failing?

2024-07-25 03:22 UTC, dab246 commented
> Hi @dab246, thanks for the PR!
> 
> I just merged one with padding - that looks to be conflicting with yours, could you please solve conflicts and make sure that checks are not failing?

@illia-romanenko  Thank your feedback. I rebase it. Please review again help me. Thanks.

2024-07-30 02:54 UTC, illia-romanenko requested changes
Nice, thanks! I added couple of questions - if we can make it simpler/leaner it could be easier to understand.

2024-07-30 02:54 UTC, illia-romanenko commented on lib/src/presentation/language_tool_text_field.dart
> +        }
Those feel a bit excessive - I think I would want it to be as close to TextField as possible to simplify working with it.

2024-07-30 02:54 UTC, illia-romanenko commented on lib/src/presentation/language_tool_text_field.dart
> +  final bool obscureText;
Do you know how it will work with obscure text?

2024-08-05 02:30 UTC, dab246 commented on lib/src/presentation/language_tool_text_field.dart
> +        }
IMO, if the user doesn't want to use `Padding` for TextField we shouldn't render a `Padding` widget into the application tree by default. It will reduce its performance.

2024-08-05 02:31 UTC, dab246 commented on lib/src/presentation/language_tool_text_field.dart
> +  final bool obscureText;
Oh, that was my mistake, we don't need it here. I will remove it at now.

2024-08-05 03:00 UTC, dab246 commented
@illia-romanenko Please review again help me. Thanks

2024-08-14 16:47 UTC, illia-romanenko commented on lib/src/presentation/language_tool_text_field.dart
> +        }
Why user can't just add padding or align themselves? Any reason we want to put it in?

2024-08-19 04:53 UTC, dab246 commented on lib/src/presentation/language_tool_text_field.dart
> +        }
In many cases, users want to use a `Container` to wrap it. But the Container already has Padding. If we always wrap it in Padding, it will lead to unnecessary widget leakage, affecting the performance of rendering the widget tree. @illia-romanenko I

2024-08-19 15:59 UTC, illia-romanenko commented on lib/src/presentation/language_tool_text_field.dart
> +        }
What I mean is that we should leave it up to a widget user to wrap it in the Padding and not include padding inside LanguageToolTextField itself.

2024-08-19 17:28 UTC, dab246 commented on lib/src/presentation/language_tool_text_field.dart
> +        }
I agree with you. Let's delete it. Right?

2024-08-19 17:30 UTC, illia-romanenko commented on lib/src/presentation/language_tool_text_field.dart
> +        }
Yes, thank you!

2024-08-20 02:26 UTC, dab246 commented on lib/src/presentation/language_tool_text_field.dart
> +        }
@illia-romanenko  I updated it. Please review again help me. Thanks

2024-09-18 04:02 UTC, dab246 commented
@illia-romanenko  Did you forget this PR?

2024-09-18 14:55 UTC, illia-romanenko approved these changes
LGTM - sorry for delay. 
Thanks for your contribution!

2024-09-18 14:55 UTC, merged

2024-09-19 05:05 UTC, dab246 commented
@illia-romanenko I don't see the new version `0.1.1` on `pub.dev` but the `Changelog` file has been changed. Please check again. Thanks 

<img width="919" alt="Screenshot 2024-09-19 at 12 03 27" src="https://github.com/user-attachments/assets/a03cfb8c-ba86-44fd-9694-989d55da8e32">